export const SEQUELIZE = 'SEQUELIZE';
export const JOB_REPOSITORY = 'JOB_REPOSITORY';
export const PASSION_REPOSITORY = 'PASSION_REPOSITORY';
export const PASSION_CATEGORY_REPOSITORY = 'PASSION_CATEGORY_REPOSITORY';
export const UNIVERSITY_REPOSITORY = 'UNIVERSITY_REPOSITORY';